### ISSUE TITLE
excludeFieldsWithoutExposeAnnotation() -> cannot resolved

### ISSUE THREAD

**Issue by Rainer-Lang** [julman99/gson-fire#10]
Same to
- registerTypeAdapter
- setExclusionStrategies

But I can still use the Gson-builder...?

**Comment by Rainer-Lang** [comment]
OK - I'm using the originally gson for all standard - and gsonfire for the topping. ;-)
All works fine! Great.

**Comment by julman99** [comment]
You can access the GsonBuilder object from the GsonFireBuilder this way

```java
GsonFireBuilder fireBuilder = new GsonFireBuilder();
//Do some stuff with fireBuilder

//Then access the standard gson bulilder, which will be already configured by GsonFireBuilder 
GsonBuilder gsonBuilder = fireBuilder.createGsonBuilder();
```

**Comment by Rainer-Lang** [comment]
Seen this and also using. Thanks for reply!
All works great.
