### ISSUE TITLE
Add support for one-way serialization

### ISSUE THREAD

**Issue by julman99** [julman99/gson-fire#12]
The idea would be to annotate a field like with something similar to this (names might change):

```java
@Expose
@OneWay(OneWaySerialization.serialize) 
private String someField;
```

That would cause to write ```someField``` only when serializing to json, but not when serializing from json.

The ```OneWaySerialization``` enum would have ```serialize``` and ```unserialize```

Thanks @rubioz for the idea

**Comment by lalpert** [comment]
Would this be the same as the built-in @Expose serialize/deserialize? https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/annotations/Expose.html

**Comment by julman99** [comment]
@lalpert that is correct

Closing this feature request
