### ISSUE TITLE
Support RFC3339 full-date

### ISSUE THREAD

**Issue by WonderCsabo** [julman99/gson-fire#19]
The [standard](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) supports a `full-date` format, which only contains date information, and does not have any time and timezone information. Currently the date serialiser rejects dates coming in this format. It would be also nice to add an option to the deserializer to only use `full-date` and not emit any time information, so consumers can accept the generated string even if they strictly only use the `full-date` part.

This `full-date` format is used by lots of frameworks like [Swagger](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types) as default date type. Currently GSON Fire cannot work with them, because it expects and generates `date-time`.

BTW, `full-time` support can be also added, but that is less used.

**Comment by julman99** [comment]
Thanks for the suggestion. Do you expect these values to be serialized from-to ```java.util.Date```?

**Comment by WonderCsabo** [comment]
Yes.

**Comment by julman99** [comment]
Ok great I will work on this during the weekend

**Comment by julman99** [comment]
I've been working on this. I have the part that can parse a date with our without the time. The second part, (serializing only the date portion) will be done during the week. The next version of GsonFire will include this feature and will be released at the most on Oct 12th.

**Comment by WonderCsabo** [comment]
Great, thanks!

**Comment by julman99** [comment]
Done and deployed in version 1.4.0. See the ```DateSerializationPolicy```

**Comment by WonderCsabo** [comment]
Great, thanks!
