### ISSUE TITLE
Add support for date format RFC3339 (an extension of ISO 8601)

### ISSUE THREAD

**Issue by julman99** [julman99/gson-fire#2]
http://www.ietf.org/rfc/rfc3339.txt

http://en.wikipedia.org/wiki/ISO_8601

**Comment by TiagoGouvea** [comment]
The builder.setDateFormat() are not present to me.. how to create a custom simple date conversion like:

```java
builder.setDateFormat("yyyy-MM-dd HH:mm:ss");
```

Can you helpme? Thanks
