### ISSUE TITLE
DateRFC3339TypeAdapter is not thread-safe

### ISSUE THREAD

**Issue by npanasenko** [julman99/gson-fire#24]
Weird bugs appeared in my application when DateRFC3339TypeAdapter was called simultaneously from different Threads. The RFC3339DateFormat seems to cause the problem.

**Comment by julman99** [comment]
Thanks for reporting this, I will check during the weekend.

Can you be more specific on what kind of bugs you got? serialization bugs? weird exceptions?

**Comment by npanasenko** [comment]
When multiple Threads deserialize dates concurrently it is possible that the Threads return due to racing conditions wrong dates, sometimes the result of the other thread.

**Comment by julman99** [comment]
Please try version 1.5.0 and let me know if it fixes the issue

Thanks!
