### ISSUE TITLE
Reuse Exclusion Strategies

### ISSUE THREAD

**Issue by Frotty** [julman99/gson-fire#31]
Hi, is there a way to make classes that extend ExclusionByValueStrategy singleton? I profiled my app and the ExcludeLogic Class apparently gets created every time an object is being serialized, when there is really just one instance required.

**Comment by julman99** [comment]
That is a good catch! I wonder if I should cache the instance forever, or put it in a `WeakReference` and use it while it is available.

**Comment by Frotty** [comment]
Thanks for the fix!
When will you release the next version?

**Comment by julman99** [comment]
Mid oct at the latest 

Just for curiosity, was this causing performance issues for you? I assume it was the reflection invocation of `newInstance` in the class

**Comment by Frotty** [comment]
Yes, gson already creates many classes. With fire and all my stuff enabled it got up to millions of instances, Many of those were the exclusion strategies - something I couldn't really fix.

**Comment by julman99** [comment]
No snapshot, but you can clone this repo, checkout branch `v1.8.0_exclude-by-value-singleton`, change the pom version to whatever you want, do `mvn install` and then use that version in your code. Maven should resolve the dependency locally

**Comment by Frotty** [comment]
Still waiting on that 1.7.3 release 🌴

**Comment by julman99** [comment]
It's coming out tomorrow

**Comment by Frotty** [comment]
>julman99 commented 4 days ago
😢

**Comment by julman99** [comment]
I am terribly sorry for the delay. Just released version 1.8.0 and it contains the fix for this issue. Can you confirm you see an improvement?

**Comment by Frotty** [comment]
Hi I think it's fixed but I can't test it right now because my profiler license expired.

**Comment by Frotty** [comment]
Thanks again. I forgot to close.
