### ISSUE TITLE
TypeAdapter does not respect `lenient` value

### ISSUE THREAD

**Issue by Groostav** [julman99/gson-fire#35]
When using a preprocessor with a _lenient_ `gson` instance, the `FireTypeAdapter.deserialize` call fails to propagate the reader's `lenient` setting through to the `TypeAdapter`'s next `read()` call. 

The result is the below failing test:

```kt
class GsonFireFixture {

    data class SimpleThingy(val name: String, val value: Double)

    @Test fun `when deserializing nan with lenient gson should properly deserialize`(){
        val gson = GsonFireBuilder()
                .registerPreProcessor(SimpleThingy::class.java, PreProcessor { _, _, _ -> /*noop*/ })
                .createGsonBuilder()
                .setLenient() //!!!
                .create()

        val json = """{"name":"bob","value":"NaN"}"""
        val result = gson.fromJson(json, SimpleThingy::class.java) //raises exception: 
        //java.lang.NumberFormatException: JSON forbids NaN and infinities: NaN
        //	at com.google.gson.internal.bind.JsonTreeReader.nextDouble(JsonTreeReader.java:214)

        assertThat(result.value).isEqualTo(Double.NaN)
    }
}
```

_edit: the above code is kotlin, corresponding java can be supplied on request_

I'm not familiar enogh with gson to know what the correct way to do this is.

**Comment by julman99** [comment]
I'll check this today, thanks for reporting

**Comment by julman99** [comment]
Confirmed is a nasty bug, I will release a fix tonight

**Comment by julman99** [comment]
Please test version 1.8.1 and let me know if it fixes the issue for you.

Thanks again!
