### ISSUE TITLE
Missing Releases on Github

### ISSUE THREAD

**Issue by Jolter** [julman99/gson-fire#47]
Hi,
I notice that the git repo has a tag for release 1.8.3, but there is no such release listed here on Github. Also, Maven Central has 1.8.3 so it has clearly been published.
I guess this is not a big issue. I was looking for a downloadable zip of the 1.8.3 source code, but I will just clone the repo and check out that tag instead.

Thanks,
Joel

**Comment by julman99** [comment]
Fixed. I'll see if there is a way to automate this in the future
