### ISSUE TITLE
Crash on old HTC devices

### ISSUE THREAD

**Issue by TarasGordienko** [julman99/gson-fire#5]
Some HTC devices with Android 2.3 contain pre-installed old version of gson library.
Creating GsonFireBuilder on them causes a crash:
Crash Reason: 
java.lang.NoSuchMethodError:com.google.gson.GsonBuilder.registerTypeAdapterFactory

Exception Backtrace:
com.github.julman99.gsonfire.GsonFireBuilder.createGsonBuilder	 GsonFireBuilder.java, line 114

Related stackoverflow topic:
http://stackoverflow.com/questions/15609565/application-crashing-htc-explorer-a310e-when-using-gson

**Comment by jcviota** [comment]
I can confirm adding the .jar file works. Thanks for your help

**Comment by julman99** [comment]
Ok, closing then
