### ISSUE TITLE
Is this lib still maintained?

### ISSUE THREAD

**Issue by Rainer-Lang** [julman99/gson-fire#9]
I'm thinking about using this lib.

**Comment by julman99** [comment]
Hello, yes it is still maintained. No many new features have been added recently, but I am on top of bugs.

In the company I work for we use this library in production in http://contactive.com for both the Java backend and the Android app.

**Comment by Rainer-Lang** [comment]
@julman99 OK that's really helpful! :-)
Now I will test your lib for my purpose.
btw I need the lib for post processing.
Thanks.
(I'm closing this issue...)
